require("minis.misc")
require("minis.icons")
require("minis.basics")
require("minis.statusline")
require("minis.notify")
require("minis.starter")
require("minis.files")
require("minis.indentscope")
require("minis.snippets")
require("minis.tabline")
require("minis.pick")
require("minis.visitsextra")
require("minis.diff")
require("minis.git")
-- 他にkeymaps.lua で mini.pairs を require している
